// <auto-generated />
namespace MVC_GeneralStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmigrationcustomerTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigrationcustomerTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201908282029529_add-migration customerTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
